apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}
  namespace: approval-sandbox
spec:
  project: default
  source:
    helm:
      valueFiles:
        - helm/values.yaml
    repoURL: 'github.dktechin.in/torres-bro/eapproval-test'
    targetRevision: HEAD
    path: my-java-app
  destination:
    server: 'kw-sandbox-admin@kw-sandbox'
    namespace: approval-sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
