apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: approval-sandbox
  labels:
    app.kubernetes.io/name: eapproval
data:
  application.yaml: |
    # Custom application configuration
    spring:
      datasource:
        url: jdbc:mysql://mysql-service:3306/mydb
        username: root
        password: rootpassword
