apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: eapproval
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Chart.Name }}-app
