############################################################
# approval-be build github action
############################################################

name: Build DEV by Tag
on:
  push:
    branches:
      - master

env:
  # Build에 사용될 branch
  BRANCH_NAME: master
  # Dockerfile
  DOCKER_FILE: Dockerfile
  # 이미지가 저장될 Registry를 입력해주세요
  DOCKER_REGISTRY: kakaowork-common.kr-central-2.kcr.dev/tools
  # Docker 이미지 이름을 입력해주세요.
  DOCKER_IMAGE_NAME: deployment-test
  # k8s Deployment yaml
  DEPLOY_K8S_YAML: helm/templates/deployment.yaml

jobs:
  build:
    runs-on: k8s
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        with:
          ref : ${{ env.BRANCH_NAME }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.1.0
        with:
          driver : docker-container

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build And Push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            PROFILE=${{ env.BRANCH_NAME }}
          push: true
          context: .
          file: ${{ env.DOCKER_FILE }}
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
          platforms: |
            linux/amd64
          cache-from: type=gha                  # 여기서 gha 는 Guthub Actions 용 캐시를 의미합니다.
          cache-to: type=gha,mode=max

  update-deploy:
    if: ${{ success() }}
    needs:
      - build
    runs-on:
      - self-hosted
      - k8s
    steps:
      - name: Checkout Deploy YAML
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Change Deploy Yaml Files
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.24.4/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq          
          sudo chmod 664 ${{ env.DEPLOY_K8S_YAML }}
          yq e --inplace '.spec.template.spec.containers[0].image = "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}"' ${{ env.DEPLOY_K8S_YAML }}
      - name: Git Commit
        run: |
          git config --local user.email "${{github.actor}}@kakaocorp.com"
          git config --local user.name "${{github.actor}}"
          git add -A
          git commit -m " ${{ github.repository }} - Update k8s Deployment Yaml : ${{ env.DEPLOY_K8S_YAML }}" -a
      - name: Git Push
        run: |
          git push
